language: python

python:
    - "2.6"
    - "2.7"

env:
    - CC=gcc   ARCH=x86
    - CC=gcc   ARCH=x64
    - CC=clang ARCH=x86
    - CC=clang ARCH=x64

install:
    - sudo apt-get update -qq
    - sudo apt-get install libpam-dev
    - sudo apt-get install libssl-dev
    - sudo apt-get install libpcap-dev

script:
    make test

notification:
    webhooks:
      urls:
        - https://webhooks.gitter.im/e/99792de66d1b43ebb54d
      on_success: change
      on_failure: always
      on_start: false
