language: python

python:
    - "2.6"
    - "2.7"

env:
    - CC=gcc
    - CC=clang

install:
    - "pip install cpp-coveralls"
    - sudo apt-get update -qq
    - sudo apt-get install libpam-dev
    - sudo apt-get install libssl-dev
    - sudo apt-get install libpcap-dev

script:
    - make test
    - if [ "$CC" = "gcc" ]; then make coverage; fi

after_success:
    - coveralls --exclude-pattern *.h.gcov

notification:
    webhooks:
      urls:
        - https://webhooks.gitter.im/e/99792de66d1b43ebb54d
      on_success: change
      on_failure: always
      on_start: false
